# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Recipe.create(title: 'Chicken and Rice', cook_time: 120, directions: "Marinate chicken with soy sauce, lemon pepper, garlic and onion powder anywhere from 20 minute to overnight in the refrigerator.  Cook rice in water with bouillon.  This can also be done a day ahead if easier. Cook chicken in deep fry pan with just enough oil to cover the bottom. Pour out all but a few tablespoons of the oil  Return chicken to the pan and add rice a little at a time mixing to distribute evenly. Add a little more soy sauce if rice is too dry.  Finish with sesame seeds.", main_ingredient: 'Chicken', side_ingredient: 'Rice', created_at: 2015, updated_at: 2015)
Recipe.create(title: 'Sriracha Chicken and Spice Rice', cook_time: 60, directions: "Do chicken stuff, add sriracha. Add melange to rice. The spice must flow!", main_ingredient: "Chicken", side_ingredient: "Rice", created_at: 2015, updated_at: 2015 )
Recipe.create(title: 'Pepper Steak', cook_time: 20, directions: "Brown meat in a large pan sprayed with Pam. Add onion, garlic powder, and seasoned pepper. Continue to cook until the onion is translucent.  Add about three to four cups of water and the remaining ingredients except the corn starch and 3/4 cup of water. Cover and bring to a boil, reduce heat and simmer over low heat for about 2 hours. Add the sliced green pepper and cook an additional 30 minutes.  Kitchen bouquet is an ingredient that makes the gravy darker and adds flavor.  It is sold in stores near the ketchup and Tabasco sauce.  It's not necessary if you cannot find it. Ad a little more bouillon and keep in mind that the gravy will be light colored.  Mix the corn starch and water. Add slowly while constantly stirring to prevent lumping.", main_ingredient: 'Roast', side_ingredient: 'Pepper', created_at: 2015, updated_at: 2015)
Recipe.create(title: 'London Broil with Roasted Potatoes', cook_time: 60, directions: "Mix together all ingredients except the meat. Score the meat diagonally. Pour marinade over meat.  Marinate at least three to six hours or overnight. Grill until done to your preference. Directions (potatoes): Preheat the oven to 400 degrees F. Cut the potatoes in half or quarters and place in a bowl with the olive oil, salt, pepper, garlic and rosemary; toss until the potatoes are well coated. Dump the potatoes on a baking sheet and spread out into 1 layer; roast in the oven for at least 1 hour, or until browned and crisp. Flip twice with a spatula during cooking to ensure even browning. Remove the potatoes from the oven, season to taste, and serve.", main_ingredient: 'London Broil', side_ingredient: 'Potatoes', created_at: 2015, updated_at: 2015)
Recipe.create(title: 'Chicken Rosemary & Crispy Fingerling Potatoes', cook_time: 60, directions: "Saute garlic in oil and butter. Add chicken and brown. Remove garlic and add chicken broth.  Add wine and the remaining ingredients except the cream. Bring to a boil. Reduce heat and simmer over very low heat for 45 minutes. Remove chicken. Strain broth if you don't want the rosemary in the broth. Bring to a boil and cook to reduce it.  Cool slightly and add 1/3 cup of cream. Serve sauce over chicken.", main_ingredient: 'Chicken', side_ingredient: 'Potatoes', created_at: 2015, updated_at: 2015)
Recipe.create(title: 'Smothered Pork Chops with cheesy smashed potatoes', cook_time: 2, directions: "Cut potatoes in half and place in a pot. Cover with water and bring to a boil. Work on the pork chops while you are waiting for the water to boil. When water boils, add the potatoes and some salt, 2 big pinches, and boil for 10 minutes or until tender. Drain and return potatoes to the hot pot. Smash potatoes with masher and combine with sour cream and cheese. When cheese melts into potatoes, add chives and salt and pepper and re-smash. Taste the potatoes and adjust seasonings.", main_ingredient: 'Pork Chops', side_ingredient: 'Potatoes', created_at: 2015, updated_at: 2015)
Recipe.create(title: 'Herb Crusted Pork Tenderloin with Chestnut and Wild Rice Pilaf', cook_time: 2, directions: "Preheat oven to 475 degrees F. Place the pork loin on a rack in a roasting pan. Combine the remaining ingredients in a small bowl. With your fingers, massage the mixture onto the pork loin, covering all of the meat and fat. Roast the pork for 30 minutes, then reduce the heat to 425 degrees F and roast for an additional hour. Test for doneness using an instant-read thermometer. When the internal temperature reaches 155 degrees F, remove the roast from the oven. Allow it to sit for about 20 minutes before carving. It will continue to cook while it rests.", main_ingredient: 'Pork Tenderloin', side_ingredient: 'Rice', created_at: 2015, updated_at: 2015)